baseURL = 'https://www.codeandbugs.com/'
languageCode = 'en-us'
title = 'CodeAndBugs'
theme = 'hugo-theme-texify'

enableGitInfo = true

[author]
email = "info@codeandbugs.com"
name = "Omar"

[markup.goldmark.renderer]
unsafe = true # enable html in markdown

[params]
since = "2015"
footnote = """
Found a mistake? Send me a <a class=link href=https://github.com/omarkohl/codeandbugs.com target=_blank rel=noopener>pull request</a> or an <a class=link href=mailto:info@codeandbugs.com>e-mail</a>.
"""
description = 'A blog about software development and ... everything else'
customCSS = ['custom.css']

[params.math]
enable = true
use = "mathjax"
